name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: |
            ${{ secrets.BASTION_KEY_LOCAL }}
            ${{ secrets.BASTION_KEY_UBUNTU }}
          ssh-known-hosts: |
            |1|54.198.240.226 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCTUd827cbZEz1z+70MSpByn27JdWsJUm9JkFRFvjGC2Fdc85gnToEiSxeEp9TynBhaSvuYXzMgK0cmnIrKC1nmcRBk3Oq7kdwbl8S8MPoT2GN+d40WapEB+yOCImBkgIob+k+L0IubjZbMs5cljYentK10skC9wA13VBLVDxsnzH1cIE5QOAlB8yTyaS4lIozjqTFteBFv9hIFWsTfKJgVpudSu3IfY0wByevYrsaNH7FpzIibgk81uTnEPqmjKic24zgsM0s+uGQF6ewgnIoMC1NoT/SskYRAic8s6a56hZ+N0RDC6bkKAjVbGflReguj498WnS4ANyvSxwWSVo6t ec2-user@ip-10-0-1-183.ec2.internal
            |1|34.234.40.81 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDJQ9iTqJiwhvrHtqFkRL4ANYD3zl42cWYewzpNKDNnhLfKamEgKh2HpzbevXng0GgMHkTKMyNhANZbtCi+RUaPzBVjQjQJNI1Pc1nSViaovNddDoD+i0OXHjS3WBHg1II7KXxYtzMfkkjK/C88XY9m6jKPNj8LHpp5a36stUldI1Y/v9tqFgD/BTew+gbrPssRIExBNTSyaxhxnhMqgJ5/GZE7m6GNWDu+DnohUHUml5g9AX/nT9L/QdlvckcMeQgqUsRbFx8I7/OcfDS997F9LvFH2N6Drc7Aa6uBcylYazUsXqe5SDgTQFHoz+fqU9MkGJqQxr23e1aAQhuTvu5X ubuntu@ip-172-31-69-193

      - name: Deploy Code to Server
        run: |
          ssh -o StrictHostKeyChecking=no -J hikal@54.198.240.226 -i hikal ubuntu@34.234.40.81 'cd /home/ubuntu/property && git pull && npm install && npm run build'
          sudo cp -r /home/ubuntu/property/build /var/www/html/
          sudo mv /var/www/html/build /var/www/html/oldfiles
