name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: |
            ${{ secrets.BASTION_KEY_LOCAL }}
            ${{ secrets.BASTION_KEY_UBUNTU }}
          ssh-known-hosts: |
            |1|54.198.240.226 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBz31lVcnjHkOwnt1nKc9tXBAKX5jXXVWndRPYQ6slJCVJh86CASTzJFKkN8p63j6duW5nolC6309OfvfXZXGp/u7Ur4UrXndXtxnhePbwCDrICaMiua+dUfBEzbGXhnItHT6j1empxe2VoDvh/wFy8fRm/ox0HrxnXj2dC4khRkLFbmLLqz2MbFsqXRnCvjpjDmhWeyFk3nQzRokfUfMC0E6pH9GoKtZyabdHgtu3gkI8K67JZkXrHRfbEoGYmojGATU6gY3hxmifCt9XnXxLvWv2bRMDg7IKP1g9gcFIzy+EA9Lt/+n+5CHkkE6LTJEg4E9/zqXtv5Eb+IAeLCXP hikal@ip-10-0-1-183.ec2.internal
            |1|34.234.40.81 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIyh6JX0vfbocslmdFOcr06ayg3iTiG1E9pPMe220ZCJsoIsraPNWuv1EdaqLWwyjJenlLC+DCjoDxOyxR6eQYrUViEwdCQaYjnAkaz9maZm9q2XP81U/RhUiNHeJm2zaMt06+wc3W+SNQBCCoeoM1ZKYVfWHCKjERiXShebgSvPsHw+C0fJ5VwjStyDItILW5MeTbaAG0URJOIKerX+Dpi8yZxVu+qV0zQHZXc/JkHHYKPMbJf02luJdDsAOmK0StBGD+ptOUNsM8a7c7npO0C/XlQpnH95HrSHgfqHM+9mq3mS+DyArFaJ7QFpCfOvpNwadASmyUMbOKWNZ60aw3 ubuntu@ip-172-31-69-193

      - name: Deploy Code to Server
        run: |
          ssh -o StrictHostKeyChecking=no -J ubuntu@54.198.240.226 ubuntu@34.234.40.81 'cd /home/ubuntu/property && git pull && npm install && npm run build'
          sudo cp -r /home/ubuntu/property/build /var/www/html/
          sudo mv /var/www/html/build /var/www/html/oldfiles
