name: Deploy to Server

on:
  push:
    branches:
      - null

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.BASTION_KEY }}
          ssh-known-hosts: |
            |1|<54.198.240.226> <bastion-public-key>
            |1|<34.234.40.81> <target-public-key>

      - name: Deploy Code to Server
        run: |
          ssh -o StrictHostKeyChecking=no -J ubuntu@<bastion-server-ip> ubuntu@<target-server-ip> 'cd /home/ubuntu/property && git pull && npm install && npm run build'
          sudo cp -r /home/ubuntu/property/build /var/www/html/
          sudo mv /var/www/html/build /var/www/html/oldfiles
