name: Deploy to Server

on:
  push:
    branches:
      -   # Adjust the branch as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
ssh-private-key: ${{ secret_key.AAAAB3NzaC1yc2EAAAADAQABAAABAQCyiHW3799UkH5PmRTHsLh3EEYQjQSIw/vkyfpDIMPMNVuHAxRugIzlstSxmqqbEwr1oR3d2Ofr7L5606MLuo5lNucwS91gOzYPRadv584RWXSoJS2RzA0cI6wx0zm/CxamBDOnBLkhwZk0iYh/PEbchjO6NIfOacpU0lokiK/nkh7OSpfOoQglwcHhaY/mq7eVt49YhBV5Xyiwn8pzMsMn7oS2GUlr45utjS1sLEEkGtRzNcnbWBarxW0zZPq/TsCDF94E+8TCa+9f8AozVbYOD8XYEGjRClb5ljqYbYxZCSFFa9YxtWvE+g9rjgHumnEP8TQPiKjFwgcWRlqY1XPn}}

      - name: Deploy Code to Server
        run: |
          #ssh -o StrictHostKeyChecking=no ubuntu@34.234.40.81 'cd /home/ubuntu/property && git pull && npm install && npm run build'
          cd /home/ubuntu/property && git pull && npm install && npm run build
          sudo cp -r /home/ubuntu/property/build /var/www/html/
          sudo mv /var/www/html/build /var/www/html/oldfiles
          
